name: run unit tests of feature test

on: 
  push:
   branches:
     'feature/*'

jobs:
 run-unit-test:
  runs-on: ubantu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v3.3.0
   - name: run unit test
     run: run test

